Fix git script
orchestd/install pull request #7
Opened 2023-02-22 07:31 UTC by go-kipi

2023-02-22 12:25 UTC, guybrand requested changes

2023-02-22 12:25 UTC, guybrand commented on installOrchestDDocker.sh
> +	    readGithubUser;
email first
+github url
"please type the github url you will be working on for this development project:
(if its youre private github, its probably https://github/{user}, if its a company shared github, its probably something like https://github/mycompany)
 ">https://github.com/"
this means setting would have
server
email
user

2023-02-22 12:25 UTC, guybrand commented on installOrchestDDocker.sh
> +function readGithubUser {
requestGithubUser+GithubEmail

2023-02-22 12:25 UTC, guybrand commented on installOrchestDDocker.sh
> +    show "please type your github email"
e.g. mymail@gmail.com / mymail@mycompany.com

2023-02-22 12:25 UTC, guybrand commented on installOrchestDDocker.sh
> +      show "please type your github user (not email), i.e. if your github path is
please type your github user, (github -> top right corner, "Signed in as xxx")

2023-02-22 12:25 UTC, guybrand commented on installOrchestDDocker.sh
> +gitemail=$(git config user.email)
move gitemail=$(git config user.email)

to readGithubEmailFromEnv

2023-02-22 12:25 UTC, guybrand commented on installOrchestDDocker.sh
> +function readGithubMailIfNotExist {
readGithubEmailFromEnv

2023-02-22 12:25 UTC, guybrand commented on installOrchestDDocker.sh
> +    show "Need to config git  user.email"
how do I find it ?  https://github.com/settings/emails

2023-02-22 14:13 UTC, guybrand requested changes
fill in all 3 git parameter to memory
if not ALLLL exist - ask to fill in alll
if all exist - prompt if these are the parameter -> 
  yes - use the,
  no - fill in as if read git conf retuirned empty

2023-02-22 14:13 UTC, guybrand commented on installOrchestDDocker.sh
>  origpath=$PWD
line #1

2023-02-22 14:13 UTC, guybrand commented on installOrchestDDocker.sh
> +      show 'please type your github user, (github -> top right corner, "Signed in as xxx"):'
goto github.com

2023-02-22 14:13 UTC, guybrand commented on installOrchestDDocker.sh
> +  show "how do I find it ? https://github.com/settings/emails"
move to request

2023-02-22 14:59 UTC, guybrand requested changes
fill in all 3 git parameter to memory
if not ALLLL exist - ask to fill in alll
if all exist - prompt if these are the parameter -> 
  yes - use the,
  no - fill in as if read git conf retuirned empty

2023-02-22 14:59 UTC, guybrand commented on installOrchestDDocker.sh
> +    checkGitCliSshKey
move after clone apispecs + 
cd apispecs
git config user.name=
git config user.email=

2023-02-22 14:59 UTC, guybrand commented on installOrchestDDocker.sh
> +  	requestGithubUrl
move down and remove from confirmeGitParams

2023-02-26 14:56 UTC, guybrand requested changes

2023-02-26 14:56 UTC, guybrand commented on integrations/install.sh
> +    show "Need to install Go"
please install golang + link to dnd

2023-02-26 14:56 UTC, guybrand commented on integrations/install.sh
> +      echo "supported on golang 1.19+"
minimal supported version og golang is 1.19 (+link)

2023-02-26 14:56 UTC, guybrand commented on integrations/install.sh
> +        show "Need to install Git"
Please install git + link

2023-02-26 14:56 UTC, guybrand commented on integrations/install.sh
> +      show "Need to install Docker"
...

2023-02-26 14:56 UTC, guybrand commented on integrations/install.sh
> +      show "Need to install docker-compose"
...

2023-02-26 14:56 UTC, guybrand commented on integrations/install.sh
> +      show "Need to install mongo shell"
not a must, so
"for best experience, we advise you also install Mongo db tools" (+link)

2023-02-26 14:56 UTC, guybrand commented on integrations/install.sh
> +      show "Need to install mongo shell"
?

2023-02-27 14:21 UTC, orchestd approved these changes

2023-02-27 14:21 UTC, merged